package com.fatec;

import static org.junit.Assert.*;
import org.junit.Test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import org.openqa.selenium.chrome.ChromeDriver;

public class UC01ConsultaCEP {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "browserDriver/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void CT01ConsultaComSucesso() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		driver.manage().window().setSize(new Dimension(1616, 876));
		driver.findElement(By.name("UF")).click();
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("UF")).click();
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.cssSelector("span:nth-child(8) > label")).click();
		driver.findElement(By.name("Tipo")).click();
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Tipo")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).sendKeys("Orminda Pinto");
		driver.findElement(By.cssSelector(".btn2")).click();
		driver.findElement(By.cssSelector("p")).click();
		assertThat(driver.findElement(By.cssSelector("p")).getText(), is("DADOS ENCONTRADOS COM SUCESSO."));
	}

	@Test
	public void CT02ConsultaCEPcomLogradouroInvalido() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		driver.manage().window().setSize(new Dimension(1616, 876));
		driver.findElement(By.name("UF")).click();
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("UF")).click();
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		driver.findElement(By.name("Tipo")).click();
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Tipo")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).sendKeys("Uma Rua Qualquer");
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.cssSelector(".btn2")).click();
		assertThat(driver.findElement(By.cssSelector("p")).getText(), is("LOGRADOURO NAO ENCONTRADO."));
	}

	@Test
	public void CT03ConsultaCEPcomLogradouroEmBranco() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		driver.manage().window().setSize(new Dimension(1616, 876));
		driver.findElement(By.name("UF")).click();
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("UF")).click();
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		driver.findElement(By.name("Tipo")).click();
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Tipo")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Numero")).click();
		driver.findElement(By.id("Geral")).click();
		driver.findElement(By.cssSelector(".btn2")).click();
		assertThat(driver.switchTo().alert().getText(), is("Informe o logradouro !"));
	}

	@Test
	public void CT04ConsultaCEPcomLogradouroInvalido() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		driver.manage().window().setSize(new Dimension(1616, 876));
		driver.findElement(By.name("UF")).click();
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("UF")).click();
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.name("Tipo")).click();
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Tipo")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.name("Logradouro")).sendKeys("&$%%%%%");
		driver.findElement(By.cssSelector(".btn2")).click();
		driver.findElement(By.cssSelector("p")).click();
		assertThat(driver.findElement(By.cssSelector("p")).getText(), is("LOGRADOURO NAO INFORMADO/INVALIDO"));
		driver.findElement(By.cssSelector(".footer")).click();
	}

	public void espera() {
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

}
